## base configuration

baseURL = "https://www.hallajs.net"
languageCode = "en-us"
title = "hallajs.net"
paginate = 3
theme = "hugo-kiera"

## theme configuration
pygmentsCodeFences = true
disqusShortname = "inuio"
googleAnalytics = ""

[author]
name = "Muhammad Hallaj"
github = "hallaj"
gitlab = "muhammadhallaj"
linkedin = "hallajs"
twitter = "hallajs"
